### ISSUE TITLE
Extension fails to launch with `IndexError: tuple index out of range`

### ISSUE THREAD

**Issue by eloyrobillard** [cav71/syntax-highlighting-ng#1]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Extension fails to start when launching Anki.

This is linked to a PR on the original extension: https://github.com/glutanimate/syntax-highlighting/pull/42

To add some context: checking pygments' [Available Lexers](https://pygments.org/docs/lexers/) we can see that lexers like `JsonBareObjectLexer` do not have a "Short names" field (called `aliases` in the code). 

Because of this we get the error shown below.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

Anki 23.12.1

#### Error message (if any)

``` python
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.0-arm64-arm-64bit

When loading Syntax Highlighting NG:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/eloy/Library/Application Support/Anki2/addons21/566351439/__init__.py", line 24, in <module>
    from . import main  # noqa: F401
  File "/Users/eloy/Library/Application Support/Anki2/addons21/566351439/main.py", line 52, in <module>
    LANGUAGES_MAP = {lex[0]: lex[1][0] for lex in get_all_lexers()}
  File "/Users/eloy/Library/Application Support/Anki2/addons21/566351439/main.py", line 52, in <dictcomp>
    LANGUAGES_MAP = {lex[0]: lex[1][0] for lex in get_all_lexers()}
IndexError: tuple index out of range
```

**Comment by cav71** [comment]
I wrote a PR in https://github.com/cav71/syntax-highlighting-ng/pull/2 that should fix it.

Can you please try to use the artifact built in https://github.com/cav71/syntax-highlighting-ng/actions/runs/7662328847 ?
If this works, I'll upload a new addon version.
Thanks

**Comment by eloyrobillard** [comment]
Thank you for your reply! 🙇 
I got the following error when running the artifact:

``` python
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.0-arm64-arm-64bit

When loading Syntax Highlighting (NG):
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/eloy/Library/Application Support/Anki2/addons21/syntax_highlighting_ng/__init__.py", line 24, in <module>
    from . import main  # noqa: F401
  File "/Users/eloy/Library/Application Support/Anki2/addons21/syntax_highlighting_ng/main.py", line 54, in <module>
    LANGUAGES_MAP = {lex[0]: lex[1][0] for lex in get_all_lexers() if len(lex) > 1}
  File "/Users/eloy/Library/Application Support/Anki2/addons21/syntax_highlighting_ng/main.py", line 54, in <dictcomp>
    LANGUAGES_MAP = {lex[0]: lex[1][0] for lex in get_all_lexers() if len(lex) > 1}
IndexError: tuple index out of range
```

While experimenting, the following worked for me: 

``` python
{lex[0]: lex[1][0] for lex in get_all_lexers() if len(lex[1])}
```

So it looks like only the length of `lex[1]` (`aliases`) was a problem in my case. 
But keeping `len(lex) > 1` too is probably safer.

**Comment by cav71** [comment]
Thanks! I'm making changes [lates addon build](https://github.com/cav71/syntax-highlighting-ng/actions/runs/7668783842/artifacts/1197658137)

**Comment by eloyrobillard** [comment]
👍 this build works just fine

**Comment by cav71** [comment]
Just published the latest fix https://ankiweb.net/shared/info/566351439
