### ISSUE TITLE
Broken after new update?

### ISSUE THREAD

**Issue by aug-dev** [cav71/syntax-highlighting-ng#11]
Hey there!

First of all, thanks for your work on this fork.

This add-on is extremely useful.

#### Add-on Startup Failed

After updating the add-on as suggested by Anki today (May 19, 2024), it now fails to start as shown in the following image:

![Screenshot from 2024-05-19 12-32-53](https://github.com/cav71/syntax-highlighting-ng/assets/109992671/786bac50-9cba-4d2a-80f2-d77733614c83)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 -  [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki. 
 **Not really, but this is probably a Gnome specific issue**
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.8.9-200.fc39.x86_64-x86_64-with-glibc2.38

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Syntax Highlighting NG ['566351439', 2024-05-18T23:57, 'None', '']

===IDs of active AnkiWeb add-ons===
566351439

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
HyperTTS - Add speech to your flashcards ['111623432', 2024-04-15T19:11, 'None', mod]
Review Heatmap ['1771074083', 2022-06-29T22:43, 'None', '']

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Linux
- version: Fedora 39
- Package: Flatpak (from Flathub)

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://github.com/cav71/syntax-highlighting-ng/assets/109992671/f55a1816-176c-447b-825b-538f092c7f00)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.8.9-200.fc39.x86_64-x86_64-with-glibc2.38

When loading Syntax Highlighting NG:
Traceback (most recent call last):
  File "/home/augusto/.var/app/net.ankiweb.Anki/data/Anki2/addons21/566351439/__init__.py", line 26, in <module>
    from . import main  # noqa: F401
  File "/home/augusto/.var/app/net.ankiweb.Anki/data/Anki2/addons21/566351439/main.py", line 31, in <module>
    import pygments
ModuleNotFoundError: No module named 'pygments'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/home/augusto/.var/app/net.ankiweb.Anki/data/Anki2/addons21/566351439/__init__.py", line 29, in <module>
    raise RuntimeError(
RuntimeError: set env STANDALONE_ADDON=1 if you don't need anki modules


```

**Comment by cav71** [comment]
I've uploaded a new version, please check if this works. Thanks

**Comment by aug-dev** [comment]
From what I can see from a quick check, everything seems to be working now.

![image](https://github.com/cav71/syntax-highlighting-ng/assets/109992671/14eefa1d-a39c-4274-b60f-3b06d012265c)

Thanks!

**Comment by cav71** [comment]
fixed
